### ISSUE TITLE
IDEA: Is it possible to do this without a server and instead, say, with a service?

### ISSUE THREAD

**Issue by mapsam** [benbalter/problem_child#5]
This isn't an issue, but more of a question and idea. How cool would it be if you could register a repo and your github credentials at (hypothetically) `forms.github.com` that do the heavy lifting for you? I've been looking at http://formspree.io/ recently, which does amazing things - but can see a similar use-case for sending as an issue instead of email.

It could be useful for website contact forms, conference proposal ideas, etc. where having someone logged in as a github user shouldn't be required.

Maybe it's a niche case, but seems like it would be fun to build.

Thanks for putting this together :dancers:

**Comment by benbalter** [comment]
@svmatthews great suggestion. The heavy lifting here is in recreating a form building engine, a problem that's been solved a million times already, but to my knowledge, not really solved well, at least in the open source world. Anything that can output standard HTML is a candidate. Not to mention, the implementation will most likely be client side and UX-sensitive, two things I'm personally terrible at! :smile:
